language: node_js

node_js:
  - '12.6'

addons:
  apt:
    sources:
      - sourceline: deb http://toolbelt.heroku.com/ubuntu ./
      - heroku
    packages:
      - heroku

cache:
  apt: true
  directories:
    - node_modules

env:
  global:
    - ADAM=test1

deploy:
  - provider: heroku
    api_key:
      secure: L9cC1t+VcooDZjmQBTFs6BVSn1wuXb/1ewPnFkRsVIznViYJKGwDt2rWSEJtipxs7GFj7vCRxFMajk7rm1Tb7EQ8vkbyr6z7D4Pfogu5TCbSc4/rfEJmwc11SLyU69UjIb9OpCuauGMxqJdECFeLLj/cBMQ117pLfLqkeB3NSdqGQ7MKyGdAZTBAahLPbcc0ajivBabRgV52q9ixLzbvJd45h0/Juk0OIXEmv5vz5P+/Lu6EbHsezEDElv8nGrqqfJMANEgO8r0k96qKfWZ8UAwsUj5/ZNhBgRIcer+TNTC5nUm3duH6fryqgNnsS/oil/qNZj5toDibBWkzf7cFzkKMmIOz5VNR6SbGWF5aVgG9ZAHznUMN/RmVy24PSFpfGdg6MQUVwRD+oh+N9KKhnqUDDrk8TkZQ47YB/bTBzaQkgHBbwtDbJpspxmIxFoPM3EgSXIOHB+8U2ID9AYML8L9W+ZxueXeN9pJM34Z3p3eZJZe8R9pJl6wH8VWG1Xp5R5G78x0K8GWnM6CdMj7cx0FGdvqaPBqCnlhrULbVcepXgYZ087LPFd6wGmhQl1RMLZ2iMEtKf6594OP4jn/g9bDaOTJPaWfuSXct3iJ9AjNH00UYcSXeZkkqzAmLm25u2B67iwxeG73syxdoGejsjSqvIKWR6w87P0hiC0ZCrlg=
    app: tweeter-api-app
    on:
      repo: sanjiisan/twitter-api-app

  - provider: script
    skip_cleanup: true
    on:
      branch: master
    script: heroku pipelines:promote --app tweeter-api-app
