language: node_js
node_js:
  - '12.6'
before_install: 'echo "before install"'
before_script: 'echo "before script"'
install: 'echo "install"'
env:
  global:
    - ADAM=test1
  matrix:
    - PUBLICATION=bt APPNAME_STAGE=$HP4T_HEROKU_APPNAME_STAGE_BT APPNAME_PROD=$HP4T_HEROKU_APPNAME_PRODUCTION_BT
    - PUBLICATION=pub APPNAME_STAGE=$HP4T_HEROKU_APPNAME_STAGE_PUB APPNAME_PROD=$HP4T_HEROKU_APPNAME_PRODUCTION_PUB
